[package]
name = "bitcoin-ordinals-tests"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoin = { workspace = true }
base64 = { workspace = true }
hex = { workspace = true }
jsonrpsee = { workspace = true }
ord-bitcoincore-rpc = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tempfile = { workspace = true }
rooch-open-rpc-macros = { workspace = true }
jsonrpc-core = { workspace = true }