[package]
name = "moveos-decrypt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes-gcm = { workspace = true }
anyhow = { workspace = true }
byteorder = { workspace = true }
hmac = { workspace = true }
pbkdf2 = { workspace = true }
rand = { workspace = true }
rand_core = { default-features = false, workspace = true }
sha2 = { workspace = true }
